version: "3" 
services:
  backend:
    container_name: backend 
    restart: always 
    env_file:
      - "../src/backend/env/backend.env"
    build:
      context: ../src/backend 
      dockerfile: Dockerfile
    expose:
      - 5000
    command: gunicorn -w 1 -t 1000 -b 0.0.0.0:5000 wsgi:app
  nginx:
    container_name: nginx 
    restart: always 
    build:
      context: ../src/nginx 
      dockerfile: Dockerfile
    environment:
      - SKIP_PREFLIGHT_CHECK=true - SERVER_NAME=0.0.0.0
    ports:
      - 80:80 
      - 443:443
    depends_on:
      - "backend"
 
